name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          secrets: |
            authToken
            cloudflareEmail
            recordId
            zoneId
        env:
          authToken: ${{ secrets.AUTHTOKEN }}
          cloudflareEmail: ${{ secrets.CLOUDFLAREEMAIL }}
          recordId: ${{ secrets.RECORDID }}
          zoneId: ${{ secrets.ZONEID }}
